# Generated by Django 3.2.5 on 2021-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=80)),
                ('organiser', models.CharField(max_length=80)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('venue', models.TextField()),
                ('contact', models.TextField()),
                ('postCreationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
