# Generated by Django 3.2.5 on 2021-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
